package com.cjw.evolution.data.source.local.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.cjw.evolution.data.model.Token;
import com.cjw.evolution.data.model.User;

import com.cjw.evolution.data.source.local.db.TokenDao;
import com.cjw.evolution.data.source.local.db.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tokenDaoConfig;
    private final DaoConfig userDaoConfig;

    private final TokenDao tokenDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tokenDaoConfig = daoConfigMap.get(TokenDao.class).clone();
        tokenDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        tokenDao = new TokenDao(tokenDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Token.class, tokenDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        tokenDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public TokenDao getTokenDao() {
        return tokenDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
